# Build the runtime image with uv, then drop the build tooling.
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim AS base

ENV UV_COMPILE_BYTECODE=1 \
    UV_LINK_MODE=copy \
    UV_PYTHON_DOWNLOADS=never \
    PYTHONUNBUFFERED=1

WORKDIR /app

# Dependencies first, so a source edit does not re-resolve the lock.
COPY pyproject.toml uv.lock ./
RUN uv sync --locked --no-dev --no-install-project

COPY shademe ./shademe
COPY data ./data
RUN uv sync --locked --no-dev

ENV PATH="/app/.venv/bin:$PATH" \
    PORT=8011 \
    SHADEME_OUT_DIR=/data/out

# out/ holds the derived rasters and the routing graph: ~1 GB, regenerated by the
# pipeline, and NOT baked into the image. Mount it, or run the pipeline into it once.
VOLUME ["/data/out"]
EXPOSE 8011

HEALTHCHECK --interval=30s --timeout=5s --start-period=60s \
  CMD python -c "import urllib.request,os; urllib.request.urlopen(f'http://127.0.0.1:{os.environ[\"PORT\"]}/health').read()"

CMD ["sh", "-c", "uvicorn shademe.api.main:app --host 0.0.0.0 --port ${PORT}"]
