"""Validation for scripts/mrt.py. Run directly: python scripts/test_mrt.py

Synthetic inputs only -- nothing here reads out/. Sections match the brief:
  (a) UTCI vs published reference values      (d) the sun/shade x hot/cold quadrant
  (b) UTCI monotonicity                       (e) stress() shape
  (c) MRT sanity, incl. the isothermal-enclosure identity
"""
import os, sys
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import mrt as M

FAIL = []


def check(name, ok, detail=""):
    print(("  PASS  " if ok else "  FAIL  ") + name + (("   " + detail) if detail else ""))
    if not ok:
        FAIL.append(name)


def rule(t):
    print("\n" + t + "\n" + "-" * len(t))


# ---------------------------------------------------------------- (a) UTCI refs
# Two independent sets.
#  REF_PUB: the published validation table shipped with pythermalcomfort's test
#    suite, FedericoTartarini/validation-data-comfort-models v1.0.0 ts_utci.json,
#    quoted to 0.1 degC. (ta, tmrt, va, rh) -> utci
#  REF_ORACLE: generated by the coordinator from an isolated pythermalcomfort
#    3.3.0 install, also rounded to 0.1 degC.
REF_PUB = [(25, 27, 1, 50, 25.2), (19, 24, 1, 50, 20.0), (19, 14, 1, 50, 16.8),
           (27, 22, 1, 50, 25.5), (27, 22, 10, 50, 20.0), (27, 22, 16, 50, 15.8),
           (30, 27, 1, 50, 29.6), (9, 9, 1, 50, 8.7), (25, 25, 1, 50, 24.6)]
REF_ORACLE = [(30, 60, 1.0, 50, 38.0), (10, 10, 3.0, 70, 5.0), (30, 30, 1.0, 50, 30.3),
              (5, 5, 5.0, 80, -6.9), (35, 70, 2.0, 40, 43.5), (0, 0, 2.0, 80, -3.6),
              (25, 25, 0.5, 50, 24.9), (-5, -5, 1.0, 70, -6.0), (20, 20, 1.0, 60, 19.9),
              (40, 80, 1.0, 30, 50.8), (32, 32, 0.5, 50, 32.8), (28, 55, 4.0, 45, 31.4),
              (15, 40, 1.0, 50, 22.9), (12, 12, 10.0, 60, -5.0), (22, 60, 0.5, 30, 32.1)]


def _svp_log1p(ta):
    """pythermalcomfort 3.3.0's variant of the Hardy es(): log1p(T) where the
    official UTCI code, Hardy 1998 and ECMWF thermofeel all use log(T)."""
    tk = np.asarray(ta, float) + M.T0
    g = (-2.8365744e3, -6.028076559e3, 1.954263612e1, -2.737830188e-2,
         1.6261698e-5, 7.0229056e-10, -1.8680009e-13)
    es = 2.7150305 * np.log1p(tk)
    for i, gi in enumerate(g):
        es = es + gi * tk ** (i - 2)
    return np.exp(es) * 0.01


def utci_table(rows, title):
    rule(title)
    ta, tr, va, rh, exp = (np.array([r[i] for r in rows], float) for i in range(5))
    got, _ = M.utci(ta, tr, va, rh=rh)                       # ours: Hardy log(T)
    alt, _ = M.utci(ta, tr, va, vp_hpa=_svp_log1p(ta) * rh / 100.0)   # their log1p
    print("    Ta   Tmrt    va   RH | expected |    ours     diff | log1p-variant  rounds to")
    for i in range(len(rows)):
        print("  %5.1f %6.1f %5.1f %5.0f | %8.1f | %7.3f %+8.3f | %13.3f %10.1f"
              % (ta[i], tr[i], va[i], rh[i], exp[i], got[i], got[i] - exp[i],
                 alt[i], round(float(alt[i]), 1)))
    d = np.abs(got - exp)
    dalt = np.abs(np.round(alt, 1) - exp)
    print("  ours (Hardy log T)  max |diff| = %.4f degC" % d.max())
    print("  log1p variant, rounded to 0.1 as the references are: max |diff| = %.4f" % dalt.max())
    # THE coefficient test: the references were generated by pythermalcomfort, so
    # running its exact vapour-pressure formula must reproduce them bit-for-bit
    # after the 0.1 rounding they are quoted at. If a single coefficient were wrong
    # this would fail; it isolates the coefficients from the humidity conversion.
    check(title + " -- coefficients (log1p variant reproduces refs exactly)",
          dalt.max() == 0.0, "max %.4f" % dalt.max())
    check(title + " -- ours within 0.1 of published", d.max() < 0.1, "max %.4f" % d.max())
    return d.max()


rule("(a) UTCI vs published reference values")
print("  coefficients: %d terms, parsed by script from pythermalcomfort and" % len(M.UTCI_COEF))
print("  cross-checked term-by-term against ECMWF thermofeel (agreement < 1e-8 rel).")
utci_table(REF_PUB, "published table (validation-data-comfort-models v1.0.0)")
utci_table(REF_ORACLE, "coordinator oracle (pythermalcomfort 3.3.0)")

rule("(a1) which saturation vapour pressure formula is right?")
print("  Our residual against both reference sets is ~0.02-0.08 degC and one-sided.")
print("  It is NOT a coefficient error -- it is the es() formula. Measured against")
print("  published saturation vapour pressure over water (WMO/CRC), hPa:")
print("     Ta |  true e_s |  log(T) ours |  log1p(T) pythermalcomfort")
TRUE_ES = [(0, 6.112), (10, 12.28), (20, 23.39), (25, 31.69), (30, 42.46),
           (35, 56.26), (40, 73.85)]
err_ours = err_them = 0.0
for t, v in TRUE_ES:
    a, b = float(M.svp_hpa(t)), float(_svp_log1p(t))
    err_ours = max(err_ours, abs(a - v) / v)
    err_them = max(err_them, abs(b - v) / v)
    print("  %5d | %9.3f | %12.3f | %25.3f" % (t, v, a, b))
print("  max relative error:  ours %.2e   pythermalcomfort %.2e" % (err_ours, err_them))
check("our svp_hpa matches true saturation vapour pressure to <0.1%", err_ours < 1e-3,
      "%.2e" % err_ours)
print("  -> pythermalcomfort 3.3.0's log1p is an upstream bug (~0.9%% high in e_s,")
print("     ~0.03 degC in UTCI). We keep log(T). Worth reporting upstream.")

rule("(a2) reference condition Tmrt = Ta, va = 0.5 m/s, RH = 50%")
print("  UTCI tracks Ta but does NOT equal it -- the offset is a real property of")
print("  the index (it is an equivalent temperature for a reference environment),")
print("  not an error. Reported, not asserted.")
ta = np.array([-10, 0, 10, 20, 25, 30, 35], float)
u, _ = M.utci(ta, ta, 0.5, rh=50)
print("     Ta |   UTCI |  residual")
for a, b in zip(ta, u):
    print("  %5.1f | %6.2f | %+8.2f" % (a, b, b - a))
check("reference condition tracks Ta within 2 degC", np.abs(u - ta).max() < 2.0,
      "max |UTCI-Ta| = %.2f at Ta=%.0f" % (np.abs(u - ta).max(), ta[np.argmax(np.abs(u - ta))]))

# ---------------------------------------------------------------- (b) monotonic
rule("(b) UTCI monotonicity over the valid range")
ta = np.linspace(-40, 45, 25)
dt = np.linspace(-25, 60, 21)
va = np.linspace(0.5, 17, 20)
A, D, V = np.meshgrid(ta, dt, va, indexing="ij")
U, _ = M.utci(A, A + D, V, rh=50)
check("rises with Ta", np.all(np.diff(U, axis=0) > 0),
      "min dUTCI/dTa step %+.4f" % np.diff(U, axis=0).min())
check("rises with Tmrt", np.all(np.diff(U, axis=1) > 0),
      "min dUTCI/dTmrt step %+.4f" % np.diff(U, axis=1).min())

# Wind. The NET effect over the whole valid wind range is the claim that matters
# for routing, and it is clean up to Ta = 35.
ta2 = np.linspace(-40, 35, 30)
A2, D2 = np.meshgrid(ta2, dt, indexing="ij")
ulo, _ = M.utci(A2, A2 + D2, 0.5, rh=50)
uhi, _ = M.utci(A2, A2 + D2, 17.0, rh=50)
check("net: UTCI(va=17) < UTCI(va=0.5) for all Ta <= 35",
      np.all(uhi < ulo), "worst margin %+.3f degC" % (uhi - ulo).max())
hotband = (A2 >= 22)
print("  in the heat band Ta 22..35 the net wind effect is %.2f .. %.2f degC of cooling"
      % (-(uhi - ulo)[hotband].max(), -(uhi - ulo)[hotband].min()))

# LOCAL monotonicity is NOT clean, and that is upstream, not us.
A3, D3, V3 = np.meshgrid(ta2, dt, va, indexing="ij")
U3, _ = M.utci(A3, A3 + D3, V3, rh=50)
dv = np.diff(U3, axis=2) / (va[1] - va[0])            # per m/s, grid-independent
print("  local dUTCI/dva over Ta<=35: %.2f%% of steps are POSITIVE, steepest %+.3f degC/(m/s)."
      % (100.0 * (dv > 0).mean(), dv.max()))
print("  The Brode polynomial genuinely wiggles in va above Ta ~28 (it is a 6th-order")
print("  least-squares fit, not a monotone model), and above Ta ~37 the net sign")
print("  really does flip -- air hotter than skin means wind carries heat IN.")
print("  Verified against the pythermalcomfort oracle: it shows the same wiggle at")
print("  Ta=34.4 (max step +0.209 there vs our +0.208), so this is the published")
print("  polynomial's behaviour, not a transcription error.")
check("local wind wiggle stays bounded (Ta <= 35)", dv.max() < 0.5,
      "steepest +%.3f degC/(m/s), vs -1.5 degC/(m/s) for the true cooling slope"
      % dv.max())

# ---------------------------------------------------------------- (c) MRT sanity
rule("(c) MRT sanity")
T = 22.0
for svf in (0.0, 0.25, 0.5, 0.75, 1.0):
    m = M.mrt(T, svf, 1.0, 0.0, 0.0, -10.0, T, t_wall_c=T,
              eps_g=1.0, eps_w=1.0, eps_sky=1.0)
    check("(i) isothermal enclosure at %.0fC, svf=%.2f -> MRT=%.10f" % (T, svf, m),
          abs(m - T) < 1e-9)
m = M.mrt(np.full(5, T), np.linspace(0, 1, 5), 1.0, 0.0, 0.0, -10.0, T, t_wall_c=T,
          eps_g=1.0, eps_w=1.0, eps_sky=1.0)
check("(i) vectorised isothermal, max |MRT-T| = %.2e" % np.abs(m - T).max(),
      np.abs(m - T).max() < 1e-9)

# clear summer noon, Melbourne. elev 70 deg, beam 900 W/m2 normal -> ~846 horizontal.
SUN = dict(i_dir_h=846.0, i_dif=110.0, elev_deg=70.0)
m_sun = M.mrt(32.0, 1.0, 0.0, tsurf_c=52.0, rh=35, cloud=0.0, **SUN)
check("(ii) full summer sun, svf=1, hot ground -> MRT = %.1f C (want 55..70)" % m_sun,
      55.0 <= m_sun <= 70.0)
m_shade = M.mrt(32.0, 0.15, 1.0, tsurf_c=34.0, rh=35, cloud=0.0, **SUN)
check("(iii) deep shade, svf=0.15 -> MRT = %.1f C (want <= Ta+3)" % m_shade,
      m_shade <= 35.0)
print("  night, svf=1, ground at Ta-4: MRT = %.1f C (clear sky pulls MRT below Ta)"
      % M.mrt(14.0, 1.0, 1.0, 0.0, 0.0, -12.0, 10.0, rh=70, cloud=0.0))
print("  f_p(elev): " + "  ".join("%d deg=%.3f" % (b, M.f_p(b)) for b in (0, 15, 30, 45, 60, 90)))

# ---------------------------------------------------------------- (d) quadrant
rule("(d) THE QUADRANT TEST -- sun helps when cold, hurts when hot")
print("  One code path, no branches: mrt() then utci() then stress().")
print("  Sunny  = svf 0.95, shade 0.00.   Shaded = svf 0.30, shade 1.00 (tree canopy).")
DAYS = [("cold day  8C", dict(ta=8.0, rh=70.0, va=2.0, i_dir_h=430.0, i_dif=90.0,
                              elev_deg=32.0, ts_sun=16.0, ts_shade=8.0)),
        ("hot day  36C", dict(ta=36.0, rh=25.0, va=2.0, i_dir_h=846.0, i_dif=110.0,
                              elev_deg=70.0, ts_sun=58.0, ts_shade=38.0))]
EXP = [("sunny", 0.95, 0.0, "ts_sun"), ("shaded", 0.30, 1.0, "ts_shade")]
print("\n  %-12s %-7s %7s %7s %7s %8s   %s" %
      ("day", "expo", "Ta", "MRT", "UTCI", "stress", "category"))
res = {}
for dname, p in DAYS:
    for ename, svf, sh, tskey in EXP:
        tm = M.mrt(p["ta"], svf, sh, p["i_dir_h"], p["i_dif"], p["elev_deg"],
                   p[tskey], rh=p["rh"])
        u, _ = M.utci(p["ta"], tm, p["va"], rh=p["rh"])
        st = M.stress(u)
        res[(dname, ename)] = float(st)
        print("  %-12s %-7s %7.1f %7.1f %7.1f %8.2f   %s"
              % (dname, ename, p["ta"], tm, u, st, M.category(u)))
d_cold = res[("cold day  8C", "sunny")] - res[("cold day  8C", "shaded")]
d_hot = res[("hot day  36C", "sunny")] - res[("hot day  36C", "shaded")]
print("\n  delta stress (sunny - shaded):  cold day %+.2f   hot day %+.2f" % (d_cold, d_hot))
check("sun REDUCES stress on the cold day", d_cold < 0, "%+.2f" % d_cold)
check("sun INCREASES stress on the hot day", d_hot > 0, "%+.2f" % d_hot)
print("  -> the sign flip comes from the physics, not from an if-statement.")

# ---------------------------------------------------------------- (e) stress()
rule("(e) stress() shape")
u = np.linspace(-45, 55, 100001)
s = M.stress(u)
inside = (u >= 9.0) & (u <= 26.0)
check("zero inside 9..26", np.all(s[inside] == 0.0))
check("positive strictly outside", np.all(s[~inside] > 0.0))
check("continuous (max jump %.2e over a 1e-3 grid)" % np.abs(np.diff(s)).max(),
      np.abs(np.diff(s)).max() < 2e-3)
check("stress(9)==0 and stress(26)==0",
      M.stress(9.0) == 0.0 and M.stress(26.0) == 0.0)
check("symmetric slope 1 either side",
      abs(M.stress(4.0) - 5.0) < 1e-12 and abs(M.stress(31.0) - 5.0) < 1e-12)

# ---------------------------------------------------------------- clamping
rule("(f) clamping + validity flag")
u, cl = M.utci([20, 60, 20, 20], [20, 60, 20, 120], [2, 2, 0.1, 2], rh=50)
check("flags Ta>50, va<0.5, dMRT>70", list(cl) == [False, True, True, True], str(list(cl)))
uc, _ = M.utci(20, 20, 0.1, rh=50)
uk, _ = M.utci(20, 20, 0.5, rh=50)
check("clamped va=0.1 gives the va=0.5 answer (%.3f == %.3f)" % (uc, uk), abs(uc - uk) < 1e-12)
un, _ = M.utci(20, 20, 0.1, rh=50, clamp=False)
check("clamp=False extrapolates instead (%.3f != %.3f)" % (un, uk), abs(un - uk) > 1e-6)

rule("(g) shapes + speed")
check("scalar in -> 0-d out", np.ndim(M.utci(25, 25, 2, rh=50)[0]) == 0)
check("broadcasting (5,1) x (3,)", M.utci(np.full((5, 1), 25.0), 25.0,
                                          np.array([1., 2., 3.]), rh=50)[0].shape == (5, 3))
n = 200000
import time
a = np.full(n, 30.0)
t0 = time.time()
M.utci(a, a + 20, np.full(n, 2.0), rh=50)
dt1 = time.time() - t0
print("  utci over %d elements: %.2f s  (-> ~%.0f s for a 6.06M-cell raster)"
      % (n, dt1, dt1 * 6.06e6 / n))

print("\n" + "=" * 60)
print("FAILURES: %d %s" % (len(FAIL), FAIL if FAIL else ""))
sys.exit(1 if FAIL else 0)
